---
# handlers file for elk-role

- name: start elasticsearch
  service:
    name: elasticsearch
    state: started

- name: restart elasticsearch
  service: 
    name: elasticsearch
    state: restarted

